name: Build and Test Windows Forms App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Set working directory
      run: |
        cd ${{ github.workspace }}/2048WindowsFormsApp
      shell: powershell

    - name: Build
      run: msbuild /t:Build /p:Configuration=Release 2048WindowsFormsApp.sln

    - name: Test
      run: |
        # Здесь можно добавить команды для запуска тестов, если они есть
        # Пример: .\MyTests.exe

